  CC = clang++
 
  # compiler flags:
  #  -g     - this flag adds debugging information to the executable file
  #  -Wall  - this flag is used to turn on most compiler warnings
  CFLAGS  = -g -Wall
 
  assignment1:
	  $(CC) $(CFLAGS) -o q1.out encryptdecrypt.cpp
	  $(CC) $(CFLAGS) -o q2_1.out caesar_attack.cpp
	  $(CC) $(CFLAGS) -o q2_2.out vigenere_attack.cpp

